env:
    mocker: cta
replayer:
    basefiles:
        commodity: demos/common/stk_comms.json
        contract: demos/common/stocks.json
        holiday: demos/common/holidays.json
        session: demos/common/stk_sessions.json
    etime: 201912011500
    fees: demos/common/fees_stk.json
    mode: csv
    path: demos/storage/
    stime: 201909010900
